### ISSUE TITLE
Linux Server Issue

### ISSUE THREAD

**Issue by cproudlock** [Tyrox92/Gw2SPECS#44]
libQt5Network.so.5: cannot open shared object file: No such file or directory when trying to execute gw2specs_server. The library is clearly in the same directory.

**Comment by Syphdias** [comment]
Two things could be the issue here:
1. I built it with the wrong QT version (this should be fixed if this was the issue)
2. The version I built is built on amd64 architecture, what architecture are you using?

I uploaded a newly build version here:
[Gw2SPECS_Server_V2.0_Linux](https://github.com/Tyrox92/Gw2SPECS_Server/releases/download/2.0/Gw2SPECS_Server_V2.0_Linux.zip)

**Comment by oRRs** [comment]
I ran into the same issue and the "newly build version" didn't fix it.

I'm running  `3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt25-2 (2016-04-08) x86_64`

To get it running, I had to install `libqt5network5`:
`sudo apt-get install libqt5network5`
